### PR TITLE
Determine if number is odd or even in R

### PR DESCRIPTION
**Pull request by j450h1**
Please accept for hacktoberfest

### CODE REVIEW

**Comment by hmangukia** [comment]
@Pratik-Sanghani Can you review this for me? Thank you!

**Comment by j450h1** [comment]
Can someone review this please?

**Comment by Pratik-Sanghani** [comment]
Yess... @hmangukia . We are ready to merge. :)

**Comment by hmangukia** [comment]
Thank you! @Pratik-Sanghani

**Pull request merged**
